### ISSUE TITLE
Most shortcuts are crashing with other common default.

### ISSUE THREAD

**Issue by rogeriofonseca** [Julian-Heng/yabai-config#6]
How can I solve this? How do you usually solve this problem?

**Comment by julian-heng** [comment]
Hi. I'm not sure which default keybindings are conflicting. Could you please describe which ones are conflicting with the rules in the skhdrc file? Thanks.

**Comment by rogeriofonseca** [comment]
Actually, I press several combinations and nothing happens. Sometimes a shortcut is accidentally triggered when the current program has a similar shortcut.

How can you verify on the video.
![Kapture 2021-06-30 at 00 05 17](https://user-images.githubusercontent.com/1026153/123895990-1db8a180-d937-11eb-802d-f8a91fb5ed0e.gif)

**Comment by julian-heng** [comment]
I did a short recording and could not replicate the issue you're running into.

https://user-images.githubusercontent.com/22893617/123922713-e390e380-d9ba-11eb-845c-57e3ed1a9646.mov

I've also tried deliberately changing one of the rules to conflict with an existing keyboard shortcut in an application but the skhdrc rule seems to override it.

https://user-images.githubusercontent.com/22893617/123922951-1dfa8080-d9bb-11eb-932b-48020a074ab7.mov

My suggestion is to try running those commands inside of your terminal and verify that yabai is running correctly.

i.e. Running `yabai -m window --focus east` in a terminal window.

https://user-images.githubusercontent.com/22893617/123924615-b7766200-d9bc-11eb-8893-8a62aa1adfe5.mov

**Comment by rogeriofonseca** [comment]
I executed the command in terminal and it works, but through the shortcut it doesn't work. 😢 

https://user-images.githubusercontent.com/1026153/124123150-52b71800-da4d-11eb-826d-cb60d66118aa.mp4

![Screen Shot 2021-07-01 at 09 21 59](https://user-images.githubusercontent.com/1026153/124123578-d8d35e80-da4d-11eb-9961-771bf8f38088.png)

**Comment by julian-heng** [comment]
Can you verify that skhd is working by stopping it and then running `skhd` in a terminal? I notice that `¬` gets typed when you press Alt + l. I can type `¬` when I stopped skhd. I can see error messages from yabai when pressing Alt + l for example.

<img width="320" alt="Screen Shot 2021-07-01 at 10 37 40 pm" src="https://user-images.githubusercontent.com/22893617/124142632-f4c21900-dabc-11eb-9f42-0cbf2cbfaa6f.png">

**Comment by rogeriofonseca** [comment]
I really appreciate your help. 🙂🙂🙂
I found out I had another file at **"~/.config/skhd/skhdrc"** and it was reading from there causing a problem. It's working now. 🥳 

Sorry, my bad. Your help was very helpful.
