### ISSUE TITLE
how do you manage multiple display/deskstop?

### ISSUE THREAD

**Issue by sagarc03** [Julian-Heng/yabai-config#8]

**Comment by julian-heng** [comment]
I've haven't used my MacBook as much as I did 5 years ago, but I tend to have a max of 3 to 5 windows per spaces and create more spaces if necessary.

Hope that answers your question :)

**Comment by sagarc03** [comment]
so moving between spaces you use default bindings from mac?

**Comment by julian-heng** [comment]
Ah for moving between I use the Yabai bindings, but I create new spaces using the macOS Mission Control.
